const cities = [
  { id: 1, name: 'Тараз', country: 'Казахстан' },
  { id: 2, name: 'Павлодар', country: 'Казахстан' },
  { id: 3, name: 'Усть-Каменогорск', country: 'Казахстан' },
  { id: 4, name: 'Кызылорда', country: 'Казахстан' },
  { id: 5, name: 'Костанай', country: 'Казахстан' },
  { id: 6, name: 'Петропавл', country: 'Казахстан' },
  { id: 7, name: 'Астана', country: 'Казахстан' },
  { id: 8, name: 'Шымкент', country: 'Казахстан' },
  { id: 9, name: 'Алматы', country: 'Казахстан' },
  { id: 10, name: 'Кокшетау', country: 'Казахстан' },
  { id: 11, name: 'Жезказган', country: 'Казахстан' },
  { id: 12, name: 'Талдыкорган', country: 'Казахстан' },
  { id: 13, name: 'Семей', country: 'Казахстан' },
  { id: 14, name: 'Уральск', country: 'Казахстан' },
  { id: 15, name: 'Караганда', country: 'Казахстан' },
  { id: 16, name: 'Атырау', country: 'Казахстан' },
  { id: 17, name: 'Актобе', country: 'Казахстан' },
  { id: 18, name: 'Актау', country: 'Казахстан' },
  { id: 19, name: 'Экибастуз', country: 'Казахстан' },
  { id: 20, name: 'Туркестан', country: 'Казахстан' },
  { id: 21, name: 'Темиртау', country: 'Казахстан' },
  { id: 22, name: 'Байконур', country: 'Казахстан' },
  { id: 23, name: 'Кентау', country: 'Казахстан' },
  { id: 24, name: 'Балхаш', country: 'Казахстан' },
  { id: 25, name: 'Сарканд', country: 'Казахстан' },
  { id: 26, name: 'Конаев', country: 'Казахстан' },
  { id: 27, name: 'Риддер', country: 'Казахстан' },
  { id: 28, name: 'Арал', country: 'Казахстан' },
  { id: 29, name: 'Жанаозен', country: 'Казахстан' },
  { id: 30, name: 'Есик', country: 'Казахстан' },
  { id: 31, name: 'Аксу', country: 'Казахстан' },
  { id: 32, name: 'Шардара', country: 'Казахстан' },
  { id: 33, name: 'Зыряновск', country: 'Казахстан' },
  { id: 34, name: 'Жетикара', country: 'Казахстан' },
  { id: 35, name: 'Новоказалинск', country: 'Казахстан' },
  { id: 36, name: 'Шу', country: 'Казахстан' },
  { id: 37, name: 'Сарыагаш', country: 'Казахстан' },
  { id: 38, name: 'Рудный', country: 'Казахстан' },
  { id: 39, name: 'Жаркент', country: 'Казахстан' },
  { id: 40, name: 'Аягоз', country: 'Казахстан' },
  { id: 41, name: 'Атбасар', country: 'Казахстан' },
  { id: 42, name: 'Арыс', country: 'Казахстан' },
  { id: 43, name: 'Аркалык', country: 'Казахстан' },
  { id: 44, name: 'Степногорск', country: 'Казахстан' },
  { id: 45, name: 'Кандыагаш', country: 'Казахстан' },
  { id: 46, name: 'Кульсары', country: 'Казахстан' },
  { id: 47, name: 'Егиндыколь', country: 'Казахстан' },
  { id: 48, name: 'Тайынша', country: 'Казахстан' },
  { id: 49, name: 'Кировский', country: 'Казахстан' },
  { id: 50, name: 'Ассиката', country: 'Казахстан' },
  { id: 51, name: 'Теренколь', country: 'Казахстан' },
  { id: 52, name: 'Ертис', country: 'Казахстан' },
  { id: 53, name: 'Атакент', country: 'Казахстан' },
  { id: 54, name: 'Глубокое', country: 'Казахстан' },
  { id: 55, name: 'Георгиевка', country: 'Казахстан' },
  { id: 56, name: 'Ерейментау', country: 'Казахстан' },
  { id: 57, name: 'Отеген Батыр', country: 'Казахстан' },
  { id: 58, name: 'Джалагаш', country: 'Казахстан' },
  { id: 59, name: 'Дзержинское', country: 'Казахстан' },
  { id: 60, name: 'Дружба', country: 'Казахстан' },
  { id: 61, name: 'Державинск', country: 'Казахстан' },
  { id: 62, name: 'Чулаккурган', country: 'Казахстан' },
  { id: 63, name: 'Чили', country: 'Казахстан' },
  { id: 64, name: 'Бурундай', country: 'Казахстан' },
  { id: 65, name: 'Белые Воды', country: 'Казахстан' },
  { id: 66, name: 'Белоусовка', country: 'Казахстан' },
  { id: 67, name: 'Жосалы', country: 'Казахстан' },
  { id: 68, name: 'Жарык', country: 'Казахстан' },
  { id: 69, name: 'Жангатас', country: 'Казахстан' },
  { id: 70, name: 'Зайсан', country: 'Казахстан' },
  { id: 71, name: 'Яныкурган', country: 'Казахстан' },
  { id: 72, name: 'Саумалколь', country: 'Казахстан' },
  { id: 73, name: 'Турар Рыскулов', country: 'Казахстан' },
  { id: 74, name: 'Уштобе', country: 'Казахстан' },
  { id: 75, name: 'Уржар', country: 'Казахстан' },
  { id: 76, name: 'Турген', country: 'Казахстан' },
  { id: 77, name: 'Тимирязево', country: 'Казахстан' },
  { id: 78, name: 'Торгай', country: 'Казахстан' },
  { id: 79, name: 'Теренозек', country: 'Казахстан' },
  { id: 80, name: 'Темирлановка', country: 'Казахстан' },
  { id: 81, name: 'Текели', country: 'Казахстан' },
  { id: 82, name: 'Тасбугет', country: 'Казахстан' },
  { id: 83, name: 'Талгар', country: 'Казахстан' },
  { id: 84, name: 'Степняк', country: 'Казахстан' },
  { id: 85, name: 'Мырзакент', country: 'Казахстан' },
  { id: 86, name: 'Щучинск', country: 'Казахстан' },
  { id: 87, name: 'Шар', country: 'Казахстан' },
  { id: 88, name: 'Шахтинск', country: 'Казахстан' },
  { id: 89, name: 'Шахан', country: 'Казахстан' },
  { id: 90, name: 'Сарыозек', country: 'Казахстан' },
  { id: 91, name: 'Соран', country: 'Казахстан' },
  { id: 92, name: 'Качар', country: 'Казахстан' },
  { id: 93, name: 'Каражал', country: 'Казахстан' },
  { id: 94, name: 'Каратау', country: 'Казахстан' },
  { id: 95, name: 'Тугыл', country: 'Казахстан' },
  { id: 96, name: 'Первороссийский', country: 'Казахстан' },
  { id: 97, name: 'Первомайка', country: 'Казахстан' },
  { id: 98, name: 'Мынарал', country: 'Казахстан' },
  { id: 99, name: 'Курчатов', country: 'Казахстан' },
  { id: 100, name: 'Сарыкемер', country: 'Казахстан' },
];

export const sortedCities = cities.sort((a, b) => {
  const nameA = a.name.toLowerCase();
  const nameB = b.name.toLowerCase();
  return nameA.localeCompare(nameB);
});
